export const DGF_TOOL_KEY = {
  LIVE_SCORES: 'LIVE_SCORES',
  UPCOMING_EVENTS: 'UPCOMING_EVENTS',
  MANAGE_FAVOURITES: 'MANAGE_FAVOURITES',
  ADMIN_DASHBOARD: 'ADMIN_DASHBOARD',
  REGISTER: 'REGISTER',
  WELCOME: 'WELCOME',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CONFIRM_EMAIL: 'CONFIRM_EMAIL',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
} as const;

export type DgfToolKey = keyof typeof DGF_TOOL_KEY;
